info:
  component: Turbine

PREFIX:
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: 8989

management:
  port: 8990

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

turbine:
  appConfig: manage-po-api-service #accounts-api-service, manage-po-api-service
  clusterNameExpression: 'default'



